### ISSUE TITLE
콜라이더 문제

### ISSUE THREAD

**Issue by stzyoonsik** [stzhyeyun/Task6_GameFramework#10]
플레이어는 두개의 콜라이더 (펭귄 + 그림자)를 가지고 있고, 오브젝트의 충돌 처리를 그림자의 콜라이더에만 해두었는데 펭귄의 콜라이더와 충돌 시 이벤트가 발생하여 제대로 충돌처리를 할 수 없습니다.

**Comment by stzhyeyun** [comment]
Collider에 ignoreTag를 추가하였습니다. 충돌을 무시할 GameObject의 Tag를 ignoreTag로 등록하면 해당 GameObject의 Collider와는 충돌 검사를 하지 않습니다.
