### ISSUE TITLE
콜라이더가 다수의 다른 콜라이더를 감지하지 못합니다

### ISSUE THREAD

**Issue by stzyoonsik** [stzhyeyun/Task6_GameFramework#2]
플레이어의 콜라이더에서 이외의 오브젝트의 콜라이더가 1개만 감지될때는 정상 작동 하지만,
2개 이상의 다른 콜라이더가 감지될때 에러가 납니다. 
RangeError: Error #1125: The index 2 is out of range 2.

**Comment by stzhyeyun** [comment]
충돌한 오브젝트를 검사 대상 Vector에서 제거할 때, 첫 번째 제거 대상이 아닌 경우에는 실제 인덱스가 저장해 둔 인덱스와 달라 발생한 에러입니다. (removeAt() 호출 후 Vector가 빈 인덱스를 메움)
제거한 오브젝트의 개수를 누적하여 저장 인덱스에서 감산하는 형식으로 수정하였습니다.

**Comment by stzhyeyun** [comment]
지민님이 조언해주신대로 collidedIndices에 내림차순으로 접근하도록 변경하였습니다!!!
