### ISSUE TITLE
dispose 시 제대로 지우지 못하고 있습니다.

### ISSUE THREAD

**Issue by stzyoonsik** [stzhyeyun/Task6_GameFramework#3]
구름 객체가 하늘 끝까지 올라가면 지워지도록 하여 dispose();를 사용하였는데, 
TypeError: Error #1034: Type Coercion failed: cannot convert "image" to trolling.component.Component.
에러가 생깁니다

**Comment by stzjimin** [comment]
GameObject의 dispose함수내에서 Dictionary순회가 잘못되었었습니다...
아래와 같이 바꿔주세요...ㅡㅜ

``` actionscript
for(var componentType:String in _components)
            {
                var component:Component = _components[componentType];
                component.dispose();
            }
```
