### ISSUE TITLE
특정 시점의 remove 과정에서 콜라이더가 잘 지워지지 않는 문제

### ISSUE THREAD

**Issue by stzyoonsik** [stzhyeyun/Task6_GameFramework#5]
TypeError: Error #1009: Cannot access a property or method of a null object reference.

Trolling의 내부에서 이미 지워진 콜라이더와 검사를 시도해서 null 에러가 생기는 듯 합니다.

**Comment by stzhyeyun** [comment]
객체 제거 작업을 충돌 처리 이후에 하기 위해 Disposer를 만들었습니다.
충돌 시 제거되어야 하는 GameObject가 자신을 지우는 것이 아니라 Disposer의 제거 대상 목록에 추가하고, Disposer는 등록된 GameObject를 충돌 검사 단계 이후에 삭제하게 됩니다.
