### ISSUE TITLE
장애물과 충돌 이후 animationSpeed 값이 제대로 먹히지 않습니다.

### ISSUE THREAD

**Issue by stzyoonsik** [stzhyeyun/Task6_GameFramework#6]
플레이어와 장애물 충돌 시 오브젝트들의 y축 이동 속도를 0으로 한 후 서서히 최대치로 회복하게 되어있는데, animationSpeed는 회복이 되지만 애니메이션이 돌지 않는 문제가 있습니다.

**Comment by stzyoonsik** [comment]
State 클래스 안의 animationSpeed 값이 커질수록 애니메이션 재생 속도도 빨라지는 줄로 오해해서 생긴 이슈였습니다. 변수 네이밍 변경을 요청합니다.

**Comment by stzhyeyun** [comment]
**animationSpeed**를 **interval**로 변경하였습니다.
추가 : interval을 변경할 때 frameCounter는 변경하지 않아 다음 애니메이션 프레임으로 전환하는 조건을 계속적으로 만족시키지 못하는 경우가 있어 수정하였습니다.
